### ISSUE TITLE
Document an upgrade process

### ISSUE THREAD

**Issue by ironfroggy** [josegonzalez/dokku-wordpress#34] opened 2018-03-10 15:23 UTC
The instructions for setup are easy to follow, but it leaves out how to upgrade entirely. With the WordPress files in the container, Wordpress's own upgrade process fails (it just leaves your old version) and even if that were to work, an app restart would lose any of those changes.

How do we upgrade an already created app?

**Comment by victorleduc** [comment] 2018-05-08 09:37
Really good question, how can we do ?

**Comment by josegonzalez** [comment] 2018-05-08 14:23
Copy your themes and plugins into a newly generated application and push the updated one to your site. Happy to have someone PR that into the docs for this repository

**Comment by tlongren** [comment] 2018-06-21 09:30
@josegonzalez, I can update docs for this within the next couple of days. Could you assign it to me as a reminder?

**Comment by josegonzalez** [comment] 2018-06-21 12:57
You need to accept the repo invite first.

**Comment by abulka** [comment] 2018-10-27 04:02
> Copy your themes and plugins into a newly generated application and push the updated one to your site. Happy to have someone PR that into the docs for this repository

So I'm trying to update my wordpress site from 4.9.6 (which is what this dokku-wordpress repo is configured for as of Oct 2018) to 4.9.8, and don't have any custom themes or plugins.  Presumably if I had them I would download? them and put them into `wp-content` dir of the "newly generated application" that I am about to produce locally using make build:

    mv blogwp1 blogwp1_ori  # move old generated 4.9.6 app out of the way...
    export WORDPRESS_VERSION=4.9.8
    make build
    cd blogwp1  # presumably at this point I would copy in the themes and plugins if I had any?
    git push dokku master

Unfortunately my push is rejected, because my old deployed repo and the newly generated repo are two completely different git trees:

    ! [rejected]            master -> master (fetch first)
    error: failed to push some refs to 'dokku@dokku2.me:blogwp1'
    hint: Updates were rejected because the remote contains work that you do
    hint: not have locally. This is usually caused by another repository pushing
    hint: to the same ref. You may want to first integrate the remote changes

Any corrections to my steps above, and more detail on accomplishing a wordpress upgrade would be appreciated.

**Comment by josegonzalez** [comment] 2018-10-28 19:17
You can force push, or delete the new .git rep and replace with the old .git repo.

**Comment by abulka** [comment] 2018-10-28 22:27
Thanks.  Is there any reason why we can't pull the later version of wordpress straight into the existing generated repo?  The people running Wordpress on Heroku seem to take this approach.  I found these steps worked for me in upgrading the dokku generated app `mywp` to version 4.9.8 of Wordpress:

    cd mywp
    git remote set-branches --add origin 4.9.8
    git fetch origin 4.9.8:latest
    git merge -X theirs latest

If you get any conflicts `git merge-tool` and answer "d" (to delete) for each file in conflict, if any. Then `git commit` to complete the merge.

    git push dokku master

As for copying plugins into the local git repo and pushing them up - I found that this didn't work.  The plugins don't properly "arrive" at the remote due to the `dokku storage:mount` of the plugins directory issued as part of the initial deploy. This seems to give the remote wordpress site a proper persistent file system for the plugins (and uploads) directories. This is actually great since you can install plugins in situ, via the wordpress UI, and they will persist. So re plugins, basically don't worry, they persist across remote reboots and won't get affected by subsequent git pushes when upgrading.

As for themes, they will be clobbered by a git push of a new version, so the original advice of copying customized themes into the local git repo and pushing them up still applies.

**Comment by josegonzalez** [comment] 2018-10-29 02:13
No reason. If that process works for you, great. Feel free to pull request docs for any such workflow.

**Comment by josegonzalez** [comment] 2018-10-30 01:56
Closed by #39.

**Closed as completed by josegonzalez** 2018-10-30 01:56 UTC
Labels: documentation
